### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by Horst1102** [unitree-czk/capacitor-udp#2]
HI,

testing your plugin, but getting the following error when running in android simulator: 

> TypeError: Cannot read property 'create' of undefined

My code is the following: 

```
async process() {
        try {
            // await UdpPlugin.closeAllSockets();

            const info = await UdpPlugin.create();
            await UdpPlugin.bind({socketId: info.socketId, address: '0.0.0.0', port: 5500});

            await UdpPlugin.addListener('receive', data => {
                console.log('receive:', data);
            });

            await UdpPlugin.addListener('receiveError', error => {
                console.log('receiveError:', error);
            });

            await UdpPlugin.send({
                socketId: info.socketId,
                address: '226.1.1.1',
                port: 3140,
                buffer: 'hello'
            });
        } catch (e) {
            console.log('error:', e);
        }
    }
```

**Comment by unitree-czk** [comment]
This is not my problem, there is a issue when you trying to load type file.
I have myself tried many times.
my suggestion is a little bit dirty.
You can edit the file located in your node_modules/@capacitor/core/dist/esm/core-plugin-definitions.ts

Like the following.  

import { Plugin, PluginListenerHandle } from './definitions';
import {IUdpPlugin} from "capacitor-udp"

export interface PluginRegistry {
    Accessibility: AccessibilityPlugin;
    App: AppPlugin;
    BackgroundTask: BackgroundTaskPlugin;
    Browser: BrowserPlugin;
    Camera: CameraPlugin;
    Clipboard: ClipboardPlugin;
    Device: DevicePlugin;
    Filesystem: FilesystemPlugin;
    Geolocation: GeolocationPlugin;
    Haptics: HapticsPlugin;
    Keyboard: KeyboardPlugin;
    LocalNotifications: LocalNotificationsPlugin;
    Modals: ModalsPlugin;
    Motion: MotionPlugin;
    Network: NetworkPlugin;
    Permissions: PermissionsPlugin;
    Photos: PhotosPlugin;
    PushNotifications: PushNotificationsPlugin;
    Share: SharePlugin;
    SplashScreen: SplashScreenPlugin;
    StatusBar: StatusBarPlugin;
    Storage: StoragePlugin;
    Toast: ToastPlugin;
    WebView: WebViewPlugin;
    UdpPlugin: IUdpPlugin;
    [pluginName: string]: {
        [prop: string]: any;
    };
}

**Comment by unitree-czk** [comment]
Feel free to contact me with further questions.

**Comment by unitree-czk** [comment]
Dirty solution, but it works.

**Comment by WaldiirNeto** [comment]
this your solution for me did not solve

**Comment by WaldiirNeto** [comment]
my file core-plugin-definitions.d.ts :

import { Plugin, PluginListenerHandle } from './definitions';
import { IUdpPlugin } from 'capacitor-udp';
export interface PluginRegistry {
    Accessibility: AccessibilityPlugin;
    App: AppPlugin;
    BackgroundTask: BackgroundTaskPlugin;
    Browser: BrowserPlugin;
    Camera: CameraPlugin;
    Clipboard: ClipboardPlugin;
    Device: DevicePlugin;
    Filesystem: FilesystemPlugin;
    Geolocation: GeolocationPlugin;
    Haptics: HapticsPlugin;
    Keyboard: KeyboardPlugin;
    LocalNotifications: LocalNotificationsPlugin;
    Modals: ModalsPlugin;
    Motion: MotionPlugin;
    Network: NetworkPlugin;
    Permissions: PermissionsPlugin;
    Photos: PhotosPlugin;
    PushNotifications: PushNotificationsPlugin;
    Share: SharePlugin;
    SplashScreen: SplashScreenPlugin;
    StatusBar: StatusBarPlugin;
    Storage: StoragePlugin;
    Toast: ToastPlugin;
    WebView: WebViewPlugin;
    UdpPlugin:IUdpPlugin;
    [pluginName: string]: {
        [prop: string]: any;
    };
}
