### ISSUE TITLE
 problem in the Android application, does not recognize UDP plug-ins (undefined create)

### ISSUE THREAD

**Issue by WaldiirNeto** [unitree-czk/capacitor-udp#3]
I'm trying to use the capacitor-udp on android, but this error persists, I'm trying to use the capacitor-udp on android, but this error persists, I've already made the changes in core-plugin-definitions.ts and still without success

**Comment by WaldiirNeto** [comment]
reference : https://forum.ionicframework.com/t/how-to-use-capacitor-udp-plugin/182698/9

**Comment by WaldiirNeto** [comment]
versions my dependencies:
"@capacitor/android": "^1.5.1",
    "@capacitor/core": "^1.5.0",
 "typescript": "~3.4.5"

**Comment by unitree-czk** [comment]
Hi,
No offense, but did you add it to your MainActivity.java?

Like following?

    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
      add(UdpPlugin.class);
    }});

**Comment by unitree-czk** [comment]
Did you run npx cap sync first after installing the plugin?

**Comment by unitree-czk** [comment]
Hi, in your capacitor-udp plugin folder, is there a node_modules folder?
Maybe deleting this folder can help.

**Comment by WaldiirNeto** [comment]
good morning, i will do these tests on monday, thanks for answering me. I did not make this configuration on Android, because it was not in the plug-in documentation. I will do what you asked, I hope it works

**Comment by maciejmatuszak** [comment]
I found this useful:

Import section (TypeScript):
```TypeScript
import 'capacitor-udp';
import {UdpPluginUtils, IUdpPlugin} from 'capacitor-udp';
import {Plugins} from '@capacitor/core';
const {UdpPlugin} = Plugins;
```
The first line is critical, if it is not imported the plugin will not register with capacitor plugin system.

Then to use it I create I create another const plg of correct type. This helps IDE in recognising type:
```TypeScript
const plg: IUdpPlugin = UdpPlugin as IUdpPlugin;
        plg.closeAllSockets().then(() => {
            console.log('all sockets closed');
            plg.create({properties: {name: 'tello_command', bufferSize: 2048}}).then((info) => {
                this.SocketId = info.socketId;
                console.log(`Created socked : socketId: ${this.SocketId}`);
            });
        });
```
Please note there is no web implementation, so this plugin will not work when testing in web browser.

**Comment by WaldiirNeto** [comment]
thanks, i'm looking forward to testing these solutions, tomorrow i'll post the result after the tests. please leave this question open until i post my result

**Comment by unitree-czk** [comment]
> I found this useful:
> 
> Import section (TypeScript):
> 
> ```ts
> import 'capacitor-udp';
> import {UdpPluginUtils, IUdpPlugin} from 'capacitor-udp';
> import {Plugins} from '@capacitor/core';
> const {UdpPlugin} = Plugins;
> ```
> 
> The first line is critical, if it is not imported the plugin will not register with capacitor plugin system.
> 
> Then to use it I create I create another const plg of correct type. This helps IDE in recognising type:
> 
> ```ts
> const plg: IUdpPlugin = UdpPlugin as IUdpPlugin;
>         plg.closeAllSockets().then(() => {
>             console.log('all sockets closed');
>             plg.create({properties: {name: 'tello_command', bufferSize: 2048}}).then((info) => {
>                 this.SocketId = info.socketId;
>                 console.log(`Created socked : socketId: ${this.SocketId}`);
>             });
>         });
> ```
> 
> Please note there is no web implementation, so this plugin will not work when testing in web browser.

Hi， I also tried this before, sometimes it works, and sometimes doesn't. 
I strictly follow the procedure to develop the plugin, but the capacitor plugin system it self have this problem. 
........
If you use other plugins, you might face the same issue.

Am I wrong? Or is some one have better solution?

Zhongkai

**Comment by WaldiirNeto** [comment]
Well, I deleted my  `node_modules` and installed my dependencies again, ran the` npx cap sync` command and made the settings in the `core-plugins-settings.d.ts` file, but without success again, I tried to add the UdpPlugin.class to mainActivy and returned this error:
`cannot find symbol class UdpPlugin`

so I tried the example of our friend above, and the same error keeps showing up

**Comment by unitree-czk** [comment]
> Well, I deleted my `node_modules` and installed my dependencies again, ran the` npx cap sync` command and made the settings in the `core-plugins-settings.d.ts` file, but without success again, I tried to add the UdpPlugin.class to mainActivy and returned this error:
> `cannot find symbol class UdpPlugin`
> 
> so I tried the example of our friend above, and the same error keeps showing up

Firstly, the core-plugins-settings.d.ts should be in the directory /node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts

If you edit this file, it should work.
You can try removing something like   "Keyboard: KeyboardPlugin;"
If by removing it the Keybord type are no longer available, adding something like "UdpPlugin: IUdpPlugin;" should work!

**Comment by unitree-czk** [comment]
You need to make sure that "core-plugin-definitions.d.ts" is effective first!
Since there may be different  "core-plugin-definitions.d.ts"s in different folder!

**Comment by unitree-czk** [comment]
The "core-plugin-definitions.d.ts" should NOT be the one within capacitor-udp folder,
it should be within your YOUR_PROJECT/node_modules/@capacitor/core/dist/esm

**Comment by WaldiirNeto** [comment]
friend, forgive me but i know very well that it should be edited in @capacitor and i did it, however it had no effect, for now i will leave this functionality aside, and focus on other areas of the project, as soon as i get back to this situation I think of some alternative

**Comment by unitree-czk** [comment]
You can try removing something too. 
I have used this plugin in several places with vscode, and editing "core-plugin-definitions.d.ts" always is the last resort. 
No clue why it's not working in your case.

**Comment by Horst1102** [comment]
Could you provide a working example with ionic 4 or 5 via git?

**Comment by sdetweil** [comment]
so I just ran into this myself..
android

step 1. install the plugin
   npm install capacitor-udp
step 2 npx cap sync
step 3, edit the android 
add the  lines marked 
```
package io.ionic.starter;

import android.os.Bundle;

import com.getcapacitor.BridgeActivity;
import com.getcapacitor.Plugin;
import ai.unitree.udp.UdpPlugin;      // < --- add this line

import java.util.ArrayList;
public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
       add(UdpPlugin.class);                          // < add this line
    }});
  }
}
```
step 4
```
import { Plugins } from "@capacitor/core";
const { UdpPlugin } = Plugins;
```
step 5, edit the YOUR_PROJECT_PATH/node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts
and add the line 
```
UdpPlugin: IUdpPlugin;
```
as shown here
```
    Toast: ToastPlugin;
    WebView: WebViewPlugin;
    UdpPlugin: IUdpPlugin;                               // < --- this line added 
    [pluginName: string]: {
```


now you have a good UdpPlugin loaded

**Comment by theZaX** [comment]
> so I just ran into this myself..
> android
> 
> step 1. install the plugin
> npm install capacitor-udp
> step 2 npx cap sync
> step 3, edit the android
> add the lines marked
> 
> ```
> package io.ionic.starter;
> 
> import android.os.Bundle;
> 
> import com.getcapacitor.BridgeActivity;
> import com.getcapacitor.Plugin;
> import ai.unitree.udp.UdpPlugin;      // < --- add this line
> 
> import java.util.ArrayList;
> public class MainActivity extends BridgeActivity {
>   @Override
>   public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
> 
>     // Initializes the Bridge
>     this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
>       // Additional plugins you've installed go here
>       // Ex: add(TotallyAwesomePlugin.class);
>        add(UdpPlugin.class);                          // < add this line
>     }});
>   }
> }
> ```
> 
> step 4
> 
> ```
> import { Plugins } from "@capacitor/core";
> const { UdpPlugin } = Plugins;
> ```
> 
> step 5, edit the YOUR_PROJECT_PATH/node_modules/@capacitor/core/dist/esm/core-plugin-definitions.d.ts
> and add the line
> 
> ```
> UdpPlugin: IUdpPlugin;
> ```
> 
> as shown here
> 
> ```
>     Toast: ToastPlugin;
>     WebView: WebViewPlugin;
>     UdpPlugin: IUdpPlugin;                               // < --- this line added 
>     [pluginName: string]: {
> ```
> 
> now you have a good UdpPlugin loaded

Could you provide a working example using git so that it can be used as a boilerplate?
