### ISSUE TITLE
Cand send but not get any received

### ISSUE THREAD

**Issue by Horst1102** [unitree-czk/capacitor-udp#5]
Hi, i got the plugin working now and i can send a udp message succesfully. I can see the sent message with wireshark and see the expected answers. But these answers are not received by the app in my "addListener". I tested it with iOS Simulator and Android Simulator - is this the problem? Must i use it on real device? 

Here is my code: 
`
async process(command) {

        // generate random 4 chars for adding to the command
        for (let iCount=0; iCount < this.cRandom.length; iCount++){
            this.iIndex=Math.floor(Math.random() * 100)%this.iMaxRnd;
            this.cRandom[iCount]=this.cPossibleChar[this.iIndex];
        }

        try {
            await UdpPlugin.closeAllSockets();
            let info = await UdpPlugin.create();
            await UdpPlugin.bind({socketId: info.socketId, port: 3140})
            //await UdpPlugin.joinGroup({socketId: info.socketId, address: '226.1.1.1'})

            let randomString = '';
            for(let i = 0; i <=this.cRandom.length-1; i++){
                randomString = randomString+this.cRandom[i];
            }
            const commandToSend = command + '['+randomString+']'

            await UdpPlugin.addListener("receive", data => {
                console.log('received something', data);
                console.log(this.arrayBuffer2Text(UdpPluginUtils.stringToBuffer(data)));
            });

            await UdpPlugin.addListener("receiveError", error => {
                console.log('received error');
                console.log('error', error);
            });
            
            await UdpPlugin.send({
                socketId: info.socketId,
                address: '226.1.1.1',
                port: 3140,
                buffer: UdpPluginUtils.bufferToString(this.rawStringToBuffer(commandToSend))
            })

           
        } catch (e) {
            console.log(e);
        }
    }`

**Comment by unitree-czk** [comment]
Could you send me a simple example, I can test it for you on my computer.

**Comment by Horst1102** [comment]
Hi, the simple example is the code above. 

I just send a message and can see that the devices that listen for this messages on the specified address answer. But the answers are not coming to the simulating device. 


Nevermind, because we don't allow multicast over Wifi in our Company (this is default in many wifi routers out there) i will no longer try this.

**Comment by unitree-czk** [comment]
OK, wifi blocking is the possible reason, since I have developed a app using this plugin, and both works fine. For android, you can search for the app on the google store.
